### ISSUE TITLE
Detect Z folder

### ISSUE THREAD

**Issue by kavinsky** [11thmeu/launcher#3]
detect development z folder

**Comment by Thraxs** [comment]
Should be done in the last dev build. All folders that have an "addons" subfolder inside ArmA 3 folder will be detected at any level of subfolder depth. The following have been blacklisted since they are from vanilla ArmA 3 and are loaded automatically: 

Arma 3 (root), Curator, Kart, Heli, Mark

Unexpected bugs may appear, let me know if this works.

**Comment by kavinsky** [comment]
add to da list: dlcbundle
